# swagger配置
swagger:
  enable: true
  application-name: 认证模块
  application-version: v0.0.1
  application-description: 功能：登录

logging:
  level:
    com.zsl0: debug
    com.zsl: debug

# 数据源配置
datasource:
  hikari:
    username: root
    password: /e+ZDNwn1r58XyFfGWyXWQ==
    jdbc-url: jdbc:mysql://home.zsl0.com:3306/zsl0?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  redis:
    host: home.zsl0.com
    port: 6379
    password: 123456
